Sakrecoer patch 1
alephium/old-wiki pull request #46
Opened 2022-03-04 10:43 UTC by Sakrecoer

Adding a section about Desktop Wallet to the wiki

2022-03-07 08:35 UTC, nop33 requested changes
Good job @Sakrecoer, thank you for taking care of this!

I've left some comments with some feedback. 

Moreover, I noticed a few typos which would have very easily been caught by a tool like Grammarly which I highly recommend. There are desktop versions and browser extensions as well. I personally use both.

2022-03-07 08:35 UTC, nop33 commented on src/Desktop-Wallet-Guide.md
> +This is the most user-friendly option available for Wallet management. However, some could consider it slightly less privacy-preserving and secure than the node wallet as it requires you to trust the
What would you say about moving all these privacy and security concerns in their own section somewhere at the end of the article? I personally don't like that the one and only article about the desktop wallet in our wiki starts with concerns...

How about:

> # Desktop Wallet Guide
> 
> The desktop wallet is the most user-friendly Alephium wallet available today. You can download its latest version from our [GitHub](https://github.com/alephium/alephium-wallet/releases/latest).
> 
> ## Step-by-step instructions to install the desktop wallet
> ...
> 
> ## Creating a mining wallet with 4 addresses
> ...
>
> ## UTXO consolidation
> ...
>
> ## Privacy and security concerns
> Some could consider the desktop wallet slightly less privacy-preserving and secure than the node wallet as it requires you to trust the application’s security and is by default connected to a public node. However, you have the possibility to build the wallet directly from our GitHub repository and to use a local node or even create your wallet completely offline to mitigate some of these risks.

2022-03-07 08:35 UTC, nop33 commented on src/Desktop-Wallet-Guide.md
> +- Go to the [Release Page on GitHub](https://github.com/alephium/alephium-wallet/releases)
If you replace this link with https://github.com/alephium/alephium-wallet/releases/latest you always end up to the latest release.

2022-03-07 08:35 UTC, nop33 commented on src/Desktop-Wallet-Guide.md
> +- Download the executable file in line with your set-up (MAC, WINDOWS, Linux). Alternatively, if you wish and are comfortable with coding, you can build the wallet directly from our [Github repositor
The dot shouldn't be in the link :)

2022-03-07 08:35 UTC, nop33 commented on src/Desktop-Wallet-Guide.md
> +- On Linux and Windows, double click on the application to launch the Desktop wallet.
I wouldn't capitalize it: desktop wallet.

2022-03-07 08:35 UTC, nop33 commented on src/Desktop-Wallet-Guide.md
> +- To see your public address again, click on “Show address,” copy the string of characters and send it to us by email (Please make sure to use the same email you've listed in your contract).
What is this step for? Is it a copy-paste from somewhere? :)

2022-03-07 10:05 UTC, Sakrecoer commented on src/Desktop-Wallet-Guide.md
> +This is the most user-friendly option available for Wallet management. However, some could consider it slightly less privacy-preserving and secure than the node wallet as it requires you to trust the
That's brilliant! Thanks! :)

2022-03-07 10:05 UTC, Sakrecoer commented on src/Desktop-Wallet-Guide.md
> +- Go to the [Release Page on GitHub](https://github.com/alephium/alephium-wallet/releases)
Ufff!! this is  something i've been meaning to find how to achieve! Thanks! :pray:

2022-03-07 10:07 UTC, Sakrecoer commented on src/Desktop-Wallet-Guide.md
> +- To see your public address again, click on “Show address,” copy the string of characters and send it to us by email (Please make sure to use the same email you've listed in your contract).
It is indeed copy-pasted from the first  desktop wallet manual that we ever wrote. I thought i mentioned somewhere this part would probably be inaccurate today, but it looks like i didn't.

2022-03-10 10:07 UTC, nop33 commented
Hey @Sakrecoer, I've applied the changes I've requested, no need to worry about this :) I'll take care of merging this just before releasing the new version of the wallet.

2022-03-10 10:07 UTC, nop33 approved these changes

2022-03-10 10:10 UTC, Sakrecoer commented
Thank you @nop33 !

2022-04-11 14:00 UTC, nop33 commented
Closing, as content was migrated to https://github.com/alephium/wiki

2022-04-11 14:00 UTC, closed without merging